### ISSUE TITLE
Create a simple website that showcases all features

### ISSUE THREAD

**Issue by Feuerfuchs** [Feuerfuchs/sass-ignis#1]
**Todo:**

- [ ] Gather requirements
- [ ] Basic file structure and toolchain
- [ ] Ignis features
  - [ ] Property trees for variable management
  - [ ] BEM
  - [ ] Easing gradients
  - [ ] Mixins using context stacks
  - [ ] Modular scales for font sizes
